name: VANITAS WOLF
url: http://vanitaswolf.de
permalink: pretty

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      title: "VANITAS WOLF"

collections:
  works:
    output: true

#google_analytics:
#  account: UA-6031251-4
