name: VANITAS WOLF
url: http://vanitaswolf.de
permalink: pretty

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      title: "VANITAS WOLF"

collections:
  works:
    output: true

kramdown:
    parse_span_html: true
    parse_block_html: true

gems:
  - jekyll-sitemap

google_analytics:
  account: UA-3553343-1

repository: https://github.com/gwofaw/gwofaw.github.io
