name: VANITAS WOLF
title: VANITAS WOLF
author: vanitaswolf
url: http://vanitaswolf.de
description: Artwork by Anita Wolf, Karlsruhe

social:
  - name: likevanitaswolf
  - links:
    - https://www.facebook.com/likevanitaswolf
    - https://plus.google.com/116304237215637732883
    - http://www.saatchiart.com/vanitaswolf

seo:
  - type: Person
  - name: Anita Wolf
  - links:
      - https://www.facebook.com/likevanitaswolf
      - https://plus.google.com/116304237215637732883
      - http://www.saatchiart.com/vanitaswolf

facebook:
  publisher: likevanitaswolf

google_site_verification: BZEWqtVWou1GmIIGrJ8FMsQXRcLSW-nzHo9ds-7_i10

google_analytics:
  account: UA-3553343-1

repository: https://github.com/gwofaw/gwofaw.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      title: "VANITAS WOLF"

collections:
  works:
    output: true

kramdown:
    parse_span_html: true
    parse_block_html: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
