name: VANITAS WOLF
url: http://vanitaswolf.de
permalink: pretty
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      title: "VANITAS WOLF"

collections:
  works:
    output: true

kramdown:
    input: kramdown
    # parse_span_html: true
    # parse_block_html: true

google_analytics:
  account: UA-3553343-1
